### ISSUE TITLE
Travis CI is effectively dropping free CI for OSS projects

### ISSUE THREAD

**Issue by dotboris** [dotboris/alt#137]
Recently Travis CI announced that they were effectively dropping their free plan. Technically it's possible to get free access to Travis CI for OSS projects but that requires asking them nicely. I don't think that it's worth the time and effort to jump through the hoops that Travis CI has laid out here.

Currently, `alt` is running travis-ci.org which is going to go in read-only mode on December 31st. See: https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#q-what-will-happen-to-travis-ciorg-after-december-31st-2020 
We can migrate to travis-ci.com. This will give us a plan with some free credits that will eventually run out.

## Todo

- [x] Setup code quality checks with github actions
- [ ] Configure automatic release pushing with github actions
- [x] Remove travis ci config & badge
- [x] Remove all travis-ci creds

**Comment by dotboris** [comment]
## Github Actions

I've been doing a bit of digging and it seems like github actions have a fair bit of tooling that can help us. There's a `actions-rs` group that hosts a bunch of actions that can help with building rust projects.

**Comment by dotboris** [comment]
The CI for development should be fine now. There's a bunch of code quality checks. In fact, since github actions is much easier to add to than travis, I've added stuff for linting shell, python & fish

**Comment by dotboris** [comment]
All that's missing at this point is the release setup which is going to be a little more complex than just checks. That's pretty standard for releases tho.

**Comment by dotboris** [comment]
Currently, there's a half-implemented version of the release procedure in master. That's the part that's left and that needs some work / love.

**Comment by dotboris** [comment]
I'm closing this in favor of #154. The idea here is that the whole Travis CI saga is over. We're mostly migrated off.
